---
- name: Add PostgreSQL reposoitory
  yum_repository:
    name: postgresql-10
    description: postgresql yum repo
    baseurl: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/
    gpgkey:  https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-10

- name: Ensure PostgreSQL packages are installed.
  yum:
    name: postgresql10-server
    state: present

- name: Ensure PostgreSQL Python libraries are installed.
  yum:
    name: "{{ postgresql_python_library }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
